### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by PLUCS2** [sebastianss1/Artsee#1]
- [ ] Include that as part of auth users are prompted with a question on how they plan to use artsy, favorite artists, categories, etc. 
- [ ] Initial input (email, password, and name) do not appear to be editable once the account is created 
- [ ] Breakup Artists and Artworks into 2 MVP's (Institutions can go with Artists)
- [ ] Move purchasing art to the Purchasing, Likes, etc. MVP 
- [ ] Finish this sentence `Artists have artists pages with bio, notable artworks, works for sale,` 

Nice work! I am excited to see this project!

**Comment by sebastianss1** [comment]
All finished! Thanks
