### ISSUE TITLE
Sample State 

### ISSUE THREAD

**Issue by PLUCS2** [sebastianss1/Artsee#3]
- [x] Since you are saving follows do not also save a follows boolean 
- [x] Save a GalleryId rather than the name 
- [ ] Signup and login errors should just point to an Array - not an object with an array and another key value pair. Errors will only persist through that page, so the state should clear either when there is a new error or the user does what they are trying to do successfully 

Nice work! Let me know if you have any questions!

**Comment by sebastianss1** [comment]
> * [x]  Since you are saving follows do not also save a follows boolean
> * [x]  Save a GalleryId rather than the name
> * [ ]  Signup and login errors should just point to an Array - not an object with an array and another key value pair. Errors will only persist through that page, so the state should clear either when there is a new error or the user does what they are trying to do successfully
**_gotcha, please let me know if how i edited it is correct! thanks_**
> 
> Nice work! Let me know if you have any questions!
